/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var h=b.document,x=b.navigator,M="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),G=!1,E=0,z=[],N=[],s=[],g={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},e=[],A={},r=0,H=[],B=null,X={},y={},ia=null,t,Y=[].slice,ja,Z,O,k,C,$,P,ka,la,ma,I,aa,Q,R,na,J,oa,pa,qa,ra,v,sa,D,S,ta,ba,ua,va,ca,u,wa,da,T,U,xa,ya,V,za,ea,fa,Aa,ga,F,K,L,W,ha,w=function(a){try{return{init:R,hash:Q,rules:xa,hasRules:V,defaults:Aa,__qc:function(){return!0}}[a].apply(null,Y.call(arguments,1))}catch(c){return!1}};w.evts=0;w.v=2;w.SD=M;w.qpixelsent=[];U=function(a){var c=a?a.length||
0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};fa=function(a){(a=a||b._qacct)&&(ca(e,a)||e.push(a))};ca=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};da=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};T=function(a){var c,d;c=da(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};V=function(a){return ca(s,a)};Aa=function(a,c){var d;a&&((d=X[a])&&(c=
W(c,d)),c.qacct&&delete c.qacct,X[a]=c)};ga=function(a){var c,d;if(k(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?v(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=y[d])?W(c,a):a,y[d]=c);fa(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ga(a[c])};W=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||
"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ba(d,a,c);ba(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ba=function(a,c,d){var b,p,n,e,g,l;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(p=c[b],n=d[b],e="",g=!!p&&"string"==typeof p,l=!!n&&"string"==typeof n,g&&(e=p),g&&l&&(e+=","),l&&(e+=n),a[b]=e)};F=function(){var a=[],c,d;if(!(0<r)){wa();for(c in y)y.hasOwnProperty(c)&&y[c]&&(d=y[c],a.push(d),delete y[c]);1==a.length&&v(a[0]);1<a.length&&
v(a)}};K=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],g.hasOwnProperty(b.substring(2))?A[b]=5:V(b)||c.push(b);if(0===c.length)F();else for(d=0;d<c.length;d++)b=c[d],s.push(b),ua(b)};va=function(){for(var a;H[0]&&("loaded"==H[0].readyState||"complete"==H[0].readyState);)a=H.shift(),a.onreadystatechange=null,B.parentNode.insertBefore(a,B),L()};ua=function(a){var c,d;c=("https:"===h.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";B=B||h.scripts[0];r++;d=h.createElement("script");
"async"in d?(d.src=c,d.async=!1,d.onload=function(){A[a]=0;L()},d.onerror=function(){A[a]=1;L()},B.parentNode.insertBefore(d,B)):d.readyState?(A[a]=2,H.push(d),d.onreadystatechange=va,d.src=c):(A[a]=4,L())};L=function(){r-=0<r?1:0;F()};xa=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ga(c):v(c,!0)};for(c=0;c<arguments.length;c++)d=Y.call(arguments[c],0),d.splice(1,0,b),ya.apply(null,d);a=!1;G&&F()}};ya=function(a,c){var d=[],b=[],p=c||v,n,e,g,l,q;if((n=Y.call(arguments,2))&&n.length){e=
n[0]||U;g=n[1];l=n[2];n=l.length;for(q=0;q<n;q++)d.push(!1),b.push(null);d={p:a,f:d,r:e,c:l,a:g,v:b};V(a)||s.push(a);N.push(d);za(d,p)}};za=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,m;try{b=a.c[d][0],m=a.c[d].slice(1),m.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;ea(a,c)}),b.apply(null,m)}catch(e){a.f[d]=!0,a.v[d]=!1,ea(a,c)}})(b)};ea=function(a,c){var d=a.a,b=a.v,p=a.r||U,e,g,k,l,q,f;(e=U(a.f))&&(e=e&&p(b));if(e)for(b=0;b<d.length;b++)try{g=d[b][0];k=1<d[b].length?
d[b].slice(1):[];k=k.concat(a.v);l=g.apply(null,k);q={qacct:a.p,event:"rule"};for(f in l)l.hasOwnProperty(f)&&"qacct"!==f&&(q[f]=l[f]);c(q)}catch(A){}};ja=function(){return Z(0)!==Z(6)?1:0};Z=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};O=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};C="function"===typeof encodeURIComponent?encodeURIComponent:O;k=function(a){return"undefined"!=typeof a&&null!=a};$=function(){return Math.round(2147483647*
Math.random())};P=function(a){var c="",b=h.cookie,m;if(!b)return c;m=b.indexOf(a+"\x3d");a=m+a.length+1;-1<m&&(c=b.indexOf(";",a),0>c&&(c=b.length),c=b.substring(a,c));return c};ka=function(){var a="",c=I(),b,m,e;if(1===E)return";fpan\x3du;fpa\x3d";b=Q(c);for(m=0;m<M.length;m++)if(M[m]===b)return";fpan\x3du;fpa\x3d";b=new Date;m=P("__qca");if(0<m.length){try{e=+m.split("-")[2],338688E5<b-e&&(h.cookie=["__qca\x3d",m,"; expires\x3d",(new Date(e+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(g){}a+=
";fpan\x3d0;fpa\x3d"+m}0===P("__qca").length&&(m="P0-"+$()+"-"+b.getTime(),h.cookie=["__qca\x3d",m,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),m=P("__qca"),a=0<m.length?a+(";fpan\x3d1;fpa\x3d"+m):a+";fpan\x3du;fpa\x3d");return a};la=function(a){h.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+I()};I=function(){var a,c,b,e;a=h.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");e=c.length;
if(3>e)return a;b=c[e-1];return 3>b.length?a:a=c[e-2]+"."+b};aa=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};Q=function(a){var c;c=aa(2166136261,a);a=aa(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};S=function(a,c,d){var e="",p=b._qacct,g=null,h="webpage",r="load",l={},q,f,p=c?c.qacct||b._qacct:b._qacct;q=y[p];c?q&&(c=W(c,q)):c=q;p&&delete y[p];if(null!=c)for(f in c)l[f]=!0,c.hasOwnProperty(f)&&"string"===typeof f&&
"string"===typeof c[f]&&("uid"===f||"uh"===f?(na()||(g=Q(c[f])),delete c[f]):"qacct"!==f&&(0<c[f].length?e+=";"+f+a+"\x3d"+C(c[f]):l[f]=!1,"media"===f&&(h=c[f]),"event"===f&&(r=c[f])));if("string"!==typeof p){if(!k(b._qacct)||0===b._qacct.length)return"";p=b._qacct}if(p&&(q=X[p]))for(f in q)"string"===typeof f&&q.hasOwnProperty(f)&&!l[f]&&(e+=";"+f+a+"\x3d"+C(q[f]),"media"===f&&(h=q[f]),"event"===f&&(r=q[f]));l=A[p];k(l)||(l=3);e+=";rf"+a+"\x3d"+l;"string"===typeof g&&(c.uh=g,e+=";uh"+a+"\x3d"+C(g));
if("webpage"===h&&"load"===r){for(c=0;c<w.qpixelsent.length;c++)if(w.qpixelsent[c]===p&&!d)return"";w.qpixelsent.push(p)}"ad"===h&&(E=1);return";a"+a+"\x3d"+p+e};ta=function(){var a=h.getElementsByTagName("meta"),c="",b,e,g,n;for(b=0;b<a.length;b++){g=a[b];if(1E3<=c.length)return c;k(g)&&k(g.attributes)&&k(g.attributes.property)&&k(g.attributes.property.value)&&k(g.content)&&(e=g.attributes.property.value,g=g.content,3<e.length&&"og:"===e.substring(0,3)&&(0<c.length&&(c+=","),n=80<g.length?80:g.length,
c+=O(e.substring(3,e.length))+"."+O(g.substring(0,n))))}return C(c)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};na=function(){var a=!1;k(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==x.doNotTrack||"yes"===x.doNotTrack||"1"==x.msDoNotTrack};v=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",e=$(),g="",n="",A="",r="",l="",
q="u",f="1",u=0,s=[],t,v,y,B;E=0;k(w.qpixelsent)||(w.qpixelsent=[]);if(k(a))for(t in a)if("string"==typeof a[t]){n=S("",a,c);break}else"object"==typeof a[t]&&null!=a[t]&&(++u,n+=S("."+u,a[t],c));else"string"===typeof _qacct&&(n=S("",null,c));0!==n.length&&(u=x.cookieEnabled?"1":"0","undefined"!=typeof x.javaEnabled&&(q=x.javaEnabled()?"1":"0"),k(b._qmeta)&&(A=";m\x3d"+C(b._qmeta),b._qmeta=null),self.screen&&(g=screen.width+"x"+screen.height+"x"+screen.colorDepth),v=new Date,y=ja(),B=ka(),b.location&&
b.location.href&&(r=C(b.location.href)),h&&h.referrer&&(l=C(h.referrer)),b.self===b.top&&(f="0"),t=ta(),s.push("/pixel;r\x3d"+e+n+B+";ns\x3d"+f+";ce\x3d"+u),s.push(";je\x3d"+q+";sr\x3d"+g+";enc\x3d"+d+";dst\x3d"+y+";et\x3d"+v.getTime()+";tzo\x3d"+v.getTimezoneOffset()+A+";ref\x3d"+l+";url\x3d"+r+";ogl\x3d"+t),z.push(s),D())};sa=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",oa(t)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",ma(t),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&
"number"==typeof c.width&&3===c.width&&la("__qca")}};D=function(){if(t)for(;z.length;)sa(z.shift());else ra()};oa=function(a){return!0===a||1===a||1===a||k(a)&&"approved"===a.consent?!0:!1};ra=function(){if(!k(t)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){pa("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){qa("getConsent","advertising");return}t=1}D()};pa=function(a,c){t=PrivacyManagerAPI.callApi(a,"quantserve.com",
I(),"truste.com",c);D()};qa=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:I(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",J,!1);else if(b.attachEvent)b.attachEvent("onmessage",J);else{t=!0;D();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(e){}ia=setTimeout(function(){k(t)||(t=!0,D())},25)};J=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&
"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",J,!1):b.detachEvent&&window.detachEvent("onmessage",J),t=c.PrivacyManagerAPI,D())}};ha=function(){var a=arguments,c,b;u([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],v(c);e.length?K(e.slice(0)):F()};u=function(a){var c=da(a);if("array"===c)for(c=0;c<a.length;c++)u(a[c]);else"object"===c&&fa(a.qacct||b._qacct)};wa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||
v({qacct:b._qacct});if(!w.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&v(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&v(b.ezt[a]);b._qevents={push:ha};b.ezt.push=function(){var a=arguments,d;if(k(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ha.apply(this,arguments)};w.evts=1}};R=function(){var a;k(b._qevents)||(b._qevents=[]);k(b.ezt)||(b.ezt=[]);b._qoptions&&(a=T(b._qoptions),u(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=T(b.qcdata),
u(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=T(b.smarttagdata),u(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);w.evts||(b._qevents.push=function(){u([].slice.call(arguments));K(e.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){u([].slice.call(arguments));K(e.slice(0));return[].push.apply(b.ezt,arguments)});u(b.ezt);u(b._qevents);u({qacct:b._qacct});b._qoptions=null;e.length?K(e.slice(0)):F();G=!0};b.quantserve=b.quantserve||R;w.quantserve=R;
return w}(window);
try{__qc("hasRules","p-UnHP9vTbNe8QY")||function(b,h,x){try{__qc("defaults",b,{labels:"_fp.event.Default"})}catch(M){}var G=function(b,e,h){return b?"nc"===b?!e||!h||0>e.indexOf(h):"eq"===b?e===h:"sw"===b?0===e.indexOf(h):"ew"===b?(b=e.length-h.length,e=e.lastIndexOf(h,b),-1!==e&&e===b):"c"===b?0<=e.indexOf(h):!1:!1},E=function(b){var e=x.createElement("a");e.href=b;return e},z=function(b,e,s){var r;r=h.top===h.self?x.location.href:E(x.referrer).href;G(e,r,s)?b(r):b(!1)},N=function(b,e,s){var r;r=
h.top===h.self?x.location.pathname:E(x.referrer).pathname;G(e,r,s)?b(r):b(!1)},s=function(b){return"array"==={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?{labels:b.join(",")}:{labels:""+b}};__qc("rules",[b,null,[[s,"_fp.event.Savers Homepage"]],[[N,"eq","/"],[z,"c","savers"]]],[b,null,[[s,"_fp.event.Value Village Homepage"]],[[z,"c","valuevillage"],[N,"eq","/"]]],[b,null,[[s,"_fp.event.Value Village Donate Page"]],[[z,"c","valuevillage.com/donate"]]],[b,null,[[s,"_fp.event.Value Village Shop"]],
[[z,"c","valuevillage.com/shop"]]],[b,null,[[s,"_fp.event.Savers Shop"]],[[z,"c","savers.com/shop"]]],[b,null,[[s,"_fp.event.Savers Donate"]],[[z,"c","savers.com/donate"]]])}("p-UnHP9vTbNe8QY",window,document)}catch(nfe$$4){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};